version: '3.5'

services:
  tomcat:
    depends_on:
      - mongo
    image: guilhemsempere/gigwa:2.13-alpha
    ports:
      - 8080:8080 # You may amend the external port only (left hand side). By default, webapp URL will be http://host.ip:8080/gigwa
    restart: always
    environment:
      MONGO_IP: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: yourMongoRootUser
      MONGO_INITDB_ROOT_PASSWORD: yourMongoRootPassword
      HOST_LOCALE: "${LANG}"
#     casServerURL: https://sso.cirad.fr:443                # URL of the CAS server to use for Single-Sign-On
#     enforcedWebapRootUrl: http://${docker0}:8080/gigwa    # Gigwa base-URL for CAS to direct to after login. System will attempt guessing it if not provided, but it's always better to specify it
#     casOrganization: MyOrganization                       # Not required, will only be displayed on login page if provided
    volumes:
      - type: volume
        source: gigwa
        target: /usr/local/tomcat/config
#      - type: bind                      # Uncomment this line to make dumps accessible from the host machine         
#        source: /tmp/gigwaDockerDumps   # Uncomment this line to make dumps accessible from the host machine (you may also want to set the path you wish to use as source)
#        target: /root/gigwaDumps        # Uncomment this line to make dumps accessible from the host machine (must match the dumpFolder attribute's value in config.properties)

  mongo:
    image: mongo:4.2.24
#    For Apple M1/arm64, you may need to use the following image instead (uncomment the 2 lines below and comment the above line):
#    image: arm64v8/mongo:4.2.24
#    platform: linux/arm64/v8
    restart: always
    command: --profile 0 --slowms 60000 --storageEngine wiredTiger --wiredTigerCollectionBlockCompressor=zstd --directoryperdb --quiet
    ports:
      - 59393:27017 # You may amend the external port only (left hand side), which must match the above MONGO_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: yourMongoRootUser
      MONGO_INITDB_ROOT_PASSWORD: yourMongoRootPassword
    volumes:
      - type: volume
        source: mongo
        target: /data/db

volumes:
  gigwa:
  mongo: